apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-python-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: fastapi
  template:
    metadata:
      labels:
        service: fastapi
    spec:
      containers:
      - name: fastapi-service
        image: technox64/python-docker-dev-example-test:latest
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: example
        - name: POSTGRES_SERVER
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: fastapi
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
